env:
  commonjs: true
  es6: true
  node: true
  jest: true
plugins:
  - prettier
parserOptions:
  ecmaVersion: 2017
  sourceType: module
extends:
  - eslint:recommended
  - prettier
  - plugin:prettier/recommended
